[workspace]
members = ["helixdb", "helix-container", "get_routes", "helix-cli", "hbuild"]
resolver="2"

[profile.release]
strip = "debuginfo"
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
