[package]
name = "helix-cli"
version = "1.0.27"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
helixdb = { path = "../helixdb", features = ["full"] }
# helix-engine = { path = "../helix-engine" }
# helix-gateway = { path = "../helix-gateway" }
tempfile = "3.17.1"
dirs = "6.0.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
uuid = { version = "1.14.0", features = ["v4"] }
chrono = "0.4"
libc = "0.2.170"
indicatif = "0.17"
windows = { version = "0.60.0", features = ["Win32_System_Threading", "Win32_Foundation"] }


[profile.release]
lto = true
strip = true

[[bin]]
name = "helix"
path = "src/main.rs"