[package]
name = "helix-container"
version = "0.1.0"
edition = "2021"

[dependencies]
helix-engine = { path = "../helix-engine" }
protocol = { path = "../protocol" }
helix-gateway = { path = "../helix-gateway" }
helixc = { path = "../helixc" }
chrono = "0.4"
inventory = "0.3.16"
get_routes = { path = "../get_routes" }
rand = "0.8.5"
graph_queries = { path = "../graph_queries" }

[profile.release]
strip = "debuginfo"
lto = true
opt-level = "z"
