[package]
name = "proc_macros"
version = "0.1.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.104", features = ["full"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"

[features]
debug-output = []
default = []

